build:
  ios:
    commands:
      - echo "Using Node.js direct execution to avoid permission issues"
      - node node_modules/vite/bin/vite.js build
      - npx cap sync ios
    environment:
      NODE_ENV: production
      IONIC_ENV: prod
  web:
    commands:
      - node node_modules/vite/bin/vite.js build
    environment:
      NODE_ENV: production

