build:
  ios:
    commands:
      - npm install
      - npm run build
      - npx cap sync ios
    environment:
      NODE_ENV: production
      IONIC_ENV: prod

platforms:
  ios:
    buildType: release
    signing:
      certificateType: distribution
      profileType: adhoc

